### PR TITLE
Nether world name from config.yml

### PR DESCRIPTION
**Pull request by Acru**
I did this mostly for myself, and used this to help me to learn how to use github with Eclipse, but perhaps you might like to pull it in as well.  :3

It checks Bukkit's built in plugin config.yml file to get the name of the netherworld, and creates it with your default name "netherworld" if it doesn't exist.  As you can see from the commit, it is a small change and the plugin is still drop-in as before.

In any case, I hope to see this plugin improve over time~

### CODE REVIEW

**Comment by Acru** [comment]
Added a commit that contains two basic changes;

1> Portal creation has been improved greatly, finding the nearest best
available spot to place a portal along the y axis.
2> Teleport position selection has been updated to assure always
spawning in a safe place, with a fallback.

Both these use a number of added static functions to determine block types.

**Comment by SpaceManiac** [comment]
Finally got a chance to properly check out what's new. Outstanding work, I'll make sure nothing's broken and get the changes merged in as soon as possible.

**Comment by Acru** [comment]
Ah, welcome back  :3

**Comment by SpaceManiac** [comment]
Merged.

**Comment by Acru** [comment]
Ah, neat.  :3

Might have a bit of trouble trying to sort out Brettflan's commits on Nether too, though, he's been busy in the last weeks, and alot to go over, hee~

**Pull request merged**
